name: globant

dependencies:
- python=3.9.12
- pip==22.3.1
- pandas==1.5.3

- pip:
  - aws-glue-schema-registry==1.1.2
  - boto3==1.26.82
  - botocore==1.29.82
  - certifi==2022.12.7
  - fastavro==1.7.2
  - fastjsonschema==2.16.3
  - jmespath==1.0.1
  - kafka-python==  2.0.2
  - numpy==1.24.2
  - orjson==3.6.9
  - python-dateutil==2.8.2
  - pytz==2022.7.1
  - s3transfer==0.6.0
  - setuptools==65.6.3
  - six==1.16.0
  - urllib3==1.26.14
  - wheel==0.38.4